/*
 * File: app/view/agent_registration_form.js
 * Date: Wed May 15 2013 21:54:48 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.agent_registration_form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.agent_registration_form',

    config: {
        id: 'agent_registration',
        margin: 0,
        autoDestroy: false,
        items: [
            {
                xtype: 'fieldset',
                title: 'New Agent'
            },
            {
                xtype: 'fieldset',
                width: '',
                defaults: {
                    labelWidth: '45%'
                },
                title: 'Personal:',
                items: [
                    {
                        xtype: 'textfield',
                        width: '',
                        label: '*First Name:',
                        name: 'first_name'
                    },
                    {
                        xtype: 'textfield',
                        label: '*Last Name:',
                        name: 'last_name'
                    },
                    {
                        xtype: 'emailfield',
                        label: '*Email:',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'numberfield',
                        label: '*Mobile:',
                        name: 'mobile_number',
                        value: 254
                    }
                ]
            },
            {
                xtype: 'fieldset',
                width: '',
                defaults: {
                    labelWidth: '45%'
                },
                title: 'Business Details:',
                items: [
                    {
                        xtype: 'textfield',
                        width: '',
                        label: '*Business Name:',
                        name: 'business_name'
                    },
                    {
                        xtype: 'textfield',
                        width: '',
                        label: '*City/town',
                        name: 'business_location'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Address:',
                        name: 'business_address'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'agent_save',
                ui: 'confirm',
                text: 'SAVE'
            }
        ]
    }

});