/*
 * File: app/view/authentication_screen.js
 * Date: Mon May 13 2013 22:37:33 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.authentication_screen', {
    extend: 'Ext.Container',
    alias: 'widget.authentication_screen',

    config: {
        ui: '',
        layout: {
            align: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'fieldset',
                title: 'Enter Your Mobile Number:-'
            },
            {
                xtype: 'container',
                padding: '0 ',
                style: '',
                defaults: {
                    flex: 1,
                    clearIcon: false,
                    style: 'border:1px solid blue',
                    
                },
                items: [
                    {
                        xtype: 'numberfield',
                        id: 'mobile_input',
                        name: 'mobile_number',
                        value: 254
                    }
                ]
            },
            {
                xtype: 'label',
                html: 'This is the Mobile Number you registered ',
                styleHtmlContent: true
            },
            {
                xtype: 'button',
                id: 'authenticate_done',
                ui: 'confirm',
                iconAlign: 'right',
                iconCls: 'arrow_right',
                iconMask: true,
                text: 'NEXT'
            }
        ]
    }

});