/*
 * File: app/view/Authorisation_screen.js
 * Date: Tue Nov 12 2013 09:32:18 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PioneerApp.view.Authorisation_screen', {
	extend: 'Ext.form.Panel',
	alias: 'widget.authorisation_screen',

	config: {
		fullscreen: true,
		id: 'authorisation_panel',
		ui: 'light',
		layout: {
			type: 'fit'
		},
		scrollable: false,
		items: [
			{
				xtype: 'container',
				ui: '',
				layout: {
					align: 'center',
					type: 'vbox'
				},
				items: [
					{
						xtype: 'label',
						height: 110,
						hidden: false,
						html: '<img src="resources/images/pioneer_logo.png" width="150" height="90" />',
						styleHtmlContent: true
					},
					{
						xtype: 'fieldset',
						hidden: true,
						title: 'Login:'
					},
					{
						xtype: 'container',
						height: '',
						margin: 10,
						padding: 0,
						style: '',
						defaults: {
							flex: 1,
							clearIcon: false,
							style: 'border:1px solid blue',
							
						},
						items: [
							{
								xtype: 'textfield',
								id: 'mobile_input',
								labelWidth: '40%',
								name: 'userName',
								required: true,
								placeHolder: 'UserName'
							}
						]
					},
					{
						xtype: 'container',
						margin: '',
						padding: '0 3',
						style: '',
						defaults: {
							flex: 1,
							margin: 4,
							clearIcon: false,
							style: 'border:1px solid blue;',
							
						},
						layout: {
							pack: 'center',
							type: 'hbox'
						},
						items: [
							{
								xtype: 'passwordfield',
								style: 'border:1px solid blue;',
								name: 'mypasswordfield',
								placeHolder: 'Password'
							}
						]
					},
					{
						xtype: 'button',
						id: 'authorise_done',
						margin: 10,
						ui: 'confirm',
						iconAlign: 'right',
						iconCls: 'arrow_right',
						iconMask: true,
						text: 'LOGIN'
					}
				]
			}
		]
	}

});