/*
 * File: app/view/customer_registration_form.js
 * Date: Tue May 07 2013 00:36:39 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.customer_registration_form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.customer_registration_form',

    config: {
        id: 'customer_form',
        margin: 0,
        autoDestroy: false,
        items: [
            {
                xtype: 'fieldset',
                title: 'New Customer'
            },
            {
                xtype: 'fieldset',
                width: '',
                defaults: {
                    labelWidth: '45%'
                },
                instructions: '* means that the field is required. ',
                title: 'Registration:',
                items: [
                    {
                        xtype: 'textfield',
                        width: '',
                        label: '*First Name:',
                        name: 'first_name'
                    },
                    {
                        xtype: 'textfield',
                        label: '*Last Name:',
                        name: 'last_name'
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email:',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'numberfield',
                        label: '*Mobile Number',
                        name: 'mobile_number',
                        value: 254,
                        placeHolder: 'Mobile Number'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'save_customer',
                ui: 'confirm',
                text: 'SAVE'
            }
        ]
    }

});