/*
 * File: app/view/customer_dashboard.js
 * Date: Wed May 15 2013 05:37:26 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.customer_dashboard', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.user_dashboard1',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'FlexiPay',
                layout: {
                    align: 'start',
                    type: 'hbox'
                }
            },
            {
                xtype: 'container',
                title: 'Dashboard',
                iconCls: 'home',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'segmentedbutton',
                        docked: 'top',
                        itemId: 'top_segmented_button',
                        ui: '',
                        width: '',
                        scrollable: false,
                        layout: {
                            align: 'stretchmax',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                pressed: true,
                                id: 'topup_btn',
                                itemId: 'card0',
                                ui: 'small',
                                width: '',
                                iconCls: 'download',
                                iconMask: true,
                                text: 'Cash Services'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                height: 39,
                                id: 'pay_btn',
                                itemId: 'card1',
                                ui: 'small',
                                width: '',
                                iconCls: 'add',
                                iconMask: true,
                                text: 'Transfer Services'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'swap_cards',
                        itemId: 'swap_cards',
                        top: '',
                        layout: {
                            animation: 'scroll',
                            type: 'card'
                        },
                        items: [
                            {
                                xtype: 'container',
                                layout: {
                                    pack: 'center',
                                    type: 'vbox'
                                },
                                scrollable: 'vertical',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        padding: 20,
                                        defaults: {
                                            padding: 10,
                                            margin: 10
                                        },
                                        layout: {
                                            align: 'center',
                                            pack: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                action: 'give_cash', //I am to be given cash to my account
                                                ui: 'round',
                                                iconAlign: 'top',
                                                iconCls: 'favorites',
                                                iconMask: true,
                                                text: 'Deposit Money'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                action:'send_cash', //I am sending cash from my account
                                                ui: 'round',
                                                iconAlign: 'top',
                                                iconCls: 'time',
                                                iconMask: true,
                                                text: 'Withdraw Money'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        border: 0,
                                        padding: 20,
                                        defaults: {
                                            padding: 10,
                                            margin: 10
                                        },
                                        layout: {
                                            align: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                action: 'future_release',
                                                ui: 'round',
                                                iconAlign: 'top',
                                                iconCls: 'maps',
                                                iconMask: true,
                                                text: 'Mobile Money'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                ui: 'round',
                                                action:'give_cash', //I am to be given cash to my accounttype_label
                                                iconAlign: 'top',
                                                iconCls: 'team',
                                                iconMask: true,
                                                text: 'Friend Top-up'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 2,
                                        border: 1,
                                        height: '',
                                        margin: 5,
                                        style: '',
                                        ui: '',
                                        width: '',
                                        layout: {
                                            align: 'stretchmax',
                                            pack: 'center',
                                            type: 'vbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                title: 'Account Details:-'
                                            },
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: 'Logged In As:',
                                                        style: 'color:blue;'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: 'Tom Kimani',
                                                        id: 'loggedin_label',
                                                        itemId: 'loggedin_label'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: 'Account Type:',
                                                        style: 'color:blue;'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: '254729472421',
                                                        id: 'accounttype_label',
                                                        itemId: 'accounttype_label'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    type: 'hbox'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: 'Account Balance:',
                                                        style: 'color:blue;'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        flex: 2,
                                                        html: 'Customer Account',
                                                        id: 'accountbalance_label',
                                                        itemId: 'accountbalance_label'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'container',
                                        defaults: {
                                            padding: 10,
                                            margin: 10
                                        },
                                        layout: {
                                            pack: 'center',
                                            type: 'vbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                centered: false,
                                                id: 'to_friend',
                                                margin: 20,
                                                padding: 30,
                                                ui: 'round',
                                                iconAlign: 'right',
                                                iconCls: 'arrow_right',
                                                iconMask: true,
                                                text: 'To  Friend'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                id: 'to_merchant',
                                                margin: 20,
                                                padding: 30,
                                                ui: 'round',
                                                iconAlign: 'right',
                                                iconCls: 'arrow_right',
                                                iconMask: true,
                                                text: 'To Merchant '
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                id: 'payment_enter',
                                padding: 20,
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: 'Enter Amount'
                                    },
                                    {
                                        xtype: 'container',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                id: 'payment_input',
                                                itemId: 'payment_input',
                                                style: 'border:1px solid blue'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 2,
                                        padding: 5,
                                        items: [
                                            {
                                                xtype: 'container',
                                                margin: 40,
                                                items: [
                                                    {
                                                        xtype: 'button',
                                                        id: 'amount_ok',
                                                        itemId: 'amount_ok',
                                                        margin: 10,
                                                        padding: 20,
                                                        ui: 'confirm-round',
                                                        iconAlign: 'right',
                                                        iconCls: 'arrow_right',
                                                        iconMask: true,
                                                        text: 'OK'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Transactions',
                badgeText: '2',
                iconCls: 'info',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        html: '20 Transactions | Balance: Ksh 10,000'
                    },
                    {
                        xtype: 'tabpanel',
                        flex: 5,
                        items: [
                            {
                                xtype: 'container',
                                title: 'List',
                                items: [
                                    {
                                        xtype: 'searchfield',
                                        placeHolder: 'filter'
                                    },
                                    {
                                        xtype: 'list',
                                        itemTpl: [
                                            '<div>List Item {string}</div>'
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: 'Trend'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Settings',
                iconCls: 'settings',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        width: '',
                        itemTpl: [
                            '<div>{Setting_name}</div>'
                        ],
                        store: 'Settings',
                        onItemDisclosure: true
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});