/*
 * File: app/view/introduction_carousel.js
 * Date: Thu May 02 2013 20:25:30 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.introduction_carousel', {
    extend: 'Ext.navigation.View',
    alias: 'widget.introduction_carousel',

    requires: [
        'FlexiPay.view.splash_screen'
    ],

    config: {
        ui: '',
        layout: {
            animation: 'scroll',
            type: 'card'
        },
        items: [
            {
                xtype: 'splash_screen'
            }
        ]
    }

});