/*
 * File: app/view/MyContainer8.js
 * Date: Tue Nov 12 2013 13:31:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PioneerApp.view.MyContainer8', {
	extend: 'Ext.Container',

	config: {
		items: [
			{
				xtype: 'tabpanel',
				items: [
					{
						xtype: 'container',
						title: 'Tab 1',
						html: 'Testing1',
						ui: '',
						layout: {
							type: 'fit'
						},
						items: [
							{
								xtype: 'fieldset',
								title: 'MyFieldSet4',
								items: [
									{
										xtype: 'textfield',
										label: 'Field'
									},
									{
										xtype: 'textfield',
										label: 'Field'
									}
								]
							}
						]
					},
					{
						xtype: 'container',
						title: 'Tab 2'
					},
					{
						xtype: 'container',
						title: 'Tab 3'
					}
				]
			}
		]
	}

});