/*
 * File: app/view/splash_screen.js
 * Date: Mon May 13 2013 21:42:12 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.splash_screen', {
    extend: 'Ext.Container',
    alias: 'widget.splash_screen',

    config: {
        id: 'splash',
        itemId: '',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'carousel',
                flex: 2,
                padding: '10 0',
                items: [
                    {
                        xtype: 'container',
                        border: 2,
                        cls: 'launchscreen',
                        html: '<img src="resources/images/flexipay.png" width="200" height="91" /><h1>Welcome to FlexiPay</h1><p>FlexiPay is a revolutionary  way to pay and get paid.<br/> Swipe throught to see some of the features offered. Click Next to continue</p>',
                        scrollable: false
                    },
                    {
                        xtype: 'container',
                        cls: 'launchscreen',
                        html: '<img src="resources/images/flexipay.png" width="200" height="91" /><h1>Mobile Money Intergration</h1><p>Top up your account from your mobile money account including M-PESA, AIRTEL MONEY, YU-CASH and Many more.</p>',
                        layout: {
                            align: 'center',
                            type: 'hbox'
                        }
                    },
                    {
                        xtype: 'container',
                        cls: 'launchscreen',
                        html: '<img src="resources/images/flexipay.png" width="200" height="91" /><h1>Credit Card Integration</h1><p> Connect to your Bank Account Easily by simply adding your visa-card & Mastercard to be managed inside your phone.</p>',
                        layout: {
                            align: 'center',
                            type: 'hbox'
                        }
                    },
                    {
                        xtype: 'container',
                        cls: 'launchscreen',
                        html: '<img src="resources/images/flexipay.png" width="200" height="91" /><h1>Enjoy Payment Convinience</h1><p>Enjoy the payment convinience of paying by a simple tap.!</p><br><p> Easily Keep track of your payments, get convinient statements and manage all your record keeping from your mobile.</p>',
                        layout: {
                            align: 'center',
                            type: 'hbox'
                        }
                    }
                ]
            },
            {
                xtype: 'button',
                action: 'GoNext',
                docked: 'bottom',
                itemId: 'next_button',
                margin: '0 10 10 10',
                ui: 'confirm',
                text: 'Next'
            }
        ]
    }

});