/*
 * File: app/view/userDashboardPanel.js
 * Date: Tue Nov 12 2013 11:26:42 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PioneerApp.view.userDashboardPanel', {
	extend: 'Ext.Panel',

	config: {
		items: [
			{
				xtype: 'titlebar',
				docked: 'top',
				title: 'PioneerFSA',
				items: [
					{
						xtype: 'button',
						align: 'right',
						docked: 'right',
						right: 2,
						top: 10,
						ui: 'action-small',
						text: 'LOGOUT'
					}
				]
			},
			{
				xtype: 'tabpanel',
				docked: 'bottom',
				layout: {
					animation: 'flip',
					type: 'card'
				},
				items: [
					{
						xtype: 'container',
						title: 'Transactions',
						iconCls: 'bookmarks',
						ui: '',
						items: [
							{
								xtype: 'container',
								docked: 'top',
								id: 'register_options',
								padding: '0 40px',
								autoDestroy: false,
								defaults: {
									margin: '10px',
									iconCls: 'user',
									iconMask: true
								},
								layout: {
									align: 'start',
									type: 'vbox'
								},
								scrollable: true,
								items: [
									{
										xtype: 'fieldset',
										width: 232,
										title: 'Transactions'
									},
									{
										xtype: 'button',
										flex: 1,
										height: 110,
										id: 'merchant',
										iconCls: 'add',
										iconMask: true,
										text: 'New Transactions'
									},
									{
										xtype: 'button',
										flex: 1,
										id: 'agent',
										text: 'View Transactions'
									},
									{
										xtype: 'button',
										flex: 1,
										id: 'customer',
										text: 'Customer A/C'
									}
								]
							},
							{
								xtype: 'container',
								width: 284,
								items: [
									{
										xtype: 'label',
										html: 'Logged In As:'
									},
									{
										xtype: 'label',
										html: 'Allocation Date:'
									}
								]
							}
						]
					},
					{
						xtype: 'container',
						title: 'Customers',
						iconCls: 'team'
					},
					{
						xtype: 'container',
						title: 'Settings',
						iconCls: 'settings'
					}
				],
				tabBar: {
					docked: 'bottom'
				}
			}
		]
	}

});