/*
 * File: app/view/Verification_screen.js
 * Date: Mon May 13 2013 11:22:46 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.Verification_screen', {
    extend: 'Ext.Container',

    config: {
        ui: '',
        layout: {
            align: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'fieldset',
                title: 'Enter the Verification Code:-'
            },
            {
                xtype: 'container',
                defaults: {
                    style: 'border:1px solid blue',
                    
                },
                items: [
                    {
                        xtype: 'textfield',
                        id: 'verify_input',
                        name: 'mobile_number'
                    }
                ]
            },
            {
                xtype: 'label',
                html: 'Verification has been sent via sms',
                styleHtmlContent: true
            },
            {
                xtype: 'button',
                id: 'next_verify',
                ui: 'confirm',
                iconAlign: 'right',
                iconCls: 'arrow_right',
                iconMask: true,
                text: 'NEXT'
            }
        ]
    }

});