/*
 * File: app/view/Viewport.js
 * Date: Tue Nov 12 2013 10:26:47 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PioneerApp.view.Viewport', {
	extend: 'Ext.Container',

	requires: [
		'PioneerApp.view.Authorisation_screen',
		'PioneerApp.view.customer_registration_form'
	],

	config: {
		id: 'main_viewport',
		layout: {
			type: 'card'
		},
		items: [
			{
				xtype: 'authorisation_screen'
			},
			{
				xtype: 'customer_registration_form'
			}
		]
	}

});