/*
 * File: app/view/Viewport.js
 * Date: Tue May 14 2013 12:48:22 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.view.Viewport', {
    extend: 'Ext.Container',

    requires: [
        'FlexiPay.view.introduction_carousel',
        'FlexiPay.view.Authorisation_screen',
        'FlexiPay.view.registration_options',
        'FlexiPay.view.customer_registration_form',
        'FlexiPay.view.merchant_registration_form',
        'FlexiPay.view.agent_registration_form'
    ],

    config: {
        id: 'main_viewport',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'introduction_carousel'
            },
            {
                xtype: 'authorisation_screen'
            },
            {
                xtype: 'registration_options'
            },
            {
                xtype: 'customer_registration_form'
            },
            {
                xtype: 'merchant_registration_form'
            },
            {
                xtype: 'agent_registration_form'
            }
        ]
    }

});