/*
 * File: app/model/Transaction.js
 * Date: Fri May 03 2013 11:51:41 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.model.Transaction', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'Transaction_id',
                type: 'string'
            },
            {
                name: 'transaction_type',
                type: 'string'
            },
            {
                name: 'transaction_name',
                type: 'string'
            },
            {
                name: 'transaction_date',
                type: 'date'
            },
            {
                name: 'transaction_amount',
                type: 'int'
            },
            {
                name: 'user_id',
                type: 'int'
            }
        ]
    }
});