/*
 * File: app/model/Users2.js
 * Date: Mon May 13 2013 21:23:21 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.model.Users2', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'user_id',
                type: 'auto'
            },
            {
                name: 'first_name',
                type: 'string'
            },
            {
                name: 'last_name',
                type: 'string'
            },
            {
                name: 'email',
                type: 'string'
            },
            {
                name: 'mobile_number',
                type: 'string'
            },
            {
                name: 'passcode',
                type: 'int'
            },
            {
                name: 'account_id',
                type: 'int'
            },
            {
                name: 'business_name'
            },
            {
                name: 'business_location'
            },
            {
                name: 'business_address'
            },
            {
                name: 'business_id'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://41.89.68.188/restserver/index.php/api/Flexipay_server/user/format/json',
            headers: {
                Accept: 'application/json'
            }
        },
        validations: [
            {
                type: 'email',
                message: 'Please Enter A valid Email.',
                field: 'email'
            },
            {
                type: 'presence',
                field: 'first_name'
            },
            {
                type: 'presence',
                field: 'last_name'
            },
            {
                type: 'presence',
                field: 'mobile_number'
            },
            {
                type: 'length',
                field: 'mobile_number',
                min: 12
            }
        ]
    }
});