/*
 * File: app/model/Verify.js
 * Date: Mon May 13 2013 11:06:59 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexiPay.model.Verify', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'verify_code',
                type: 'string'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://41.89.68.188/restserver/index.php/api/Flexipay_server/verify/format/json'
        }
    }
});