/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
	models: [
		'Transaction',
		'Merchants',
		'Agents',
		'Account',
		'Users2'
	],
	views: [
		'Viewport',
		'Authorisation_screen',
		'customer_dashboard',
		'userDashboardPanel',
		'MyContainer8'
	],
	controllers: [
		'main_controller',
		'UserDashboard'
	],
	name: 'PioneerApp',

	launch: function() {
		console.log(sessionStorage.sessionObject);

		//Check for Existing Session object
		if(!sessionStorage.sessionObject){
			Ext.create('PioneerApp.view.Authorisation_screen', {fullscreen: true});
		}else{
			Ext.create('PioneerApp.view.Authorisation_screen', {fullscreen: true});	
		}
	}

});
